name: blacksalt
favicon: null
layout_spectrum: 0.51309
typography_spectrum: 0.21282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#1c2939'
    - '#595556'
    - '#b8b8b8'
    - '#f1f1f1'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
