name: blacksalt
favicon: null
layout_spectrum: 0.87534
typography_spectrum: 0.75826
title: The art of Jacob Richard Hansen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f1809'
    - '#81481f'
    - '#572719'
    - '#bf8a48'
    - '#eabf9d'
  brandStrength: 0.125
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
