name: blacksalt
favicon: null
layout_spectrum: 0.68527
typography_spectrum: 0.75826
title: The art and design of Jacob Richard Hansen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efffff'
    - '#020202'
    - '#82858c'
    - '#ff9122'
    - '#7a4f20'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
