name: blacksalt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75826
title: The art of Jacob Richard Hansen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#363434'
    - '#5d5d5d'
    - '#c6bfc5'
    - '#a49ea0'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
