name: blacksalt
favicon: null
layout_spectrum: 0.87534
typography_spectrum: 0.75826
title: The art of Jacob Richard Hansen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040205'
    - '#e8ff00'
    - '#006916'
    - '#f01e01'
    - '#f69a00'
  brandStrength: 0.1875
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
