name: blacksalt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#fff959'
    - '#b25d3d'
    - '#801026'
    - '#f7a953'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
