name: blacksalt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4d494a'
    - '#9c9698'
    - '#bfb8ba'
    - '#dfdadc'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
