name: blacksalt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75826
title: 'Blacksalt: The art of Jacob Richard Hansen'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a0f09'
    - '#373121'
    - '#655f47'
    - '#a04935'
    - '#8f7552'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
