name: blacksalt
favicon: null
layout_spectrum: 0.87534
typography_spectrum: 0.75826
title: The art of Jacob Richard Hansen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b191e'
    - '#5f4d3c'
    - '#d2bd91'
    - '#8c6f47'
    - '#e5d8c4'
  brandStrength: 0.125
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
